Georgiy
Vlad-Buko/ArrayListProject pull request #13
Opened 2022-02-14 16:21 UTC by iGeorgiy97

2022-02-14 22:48 UTC, JustShooter requested changes
В целом нормально, но внеси изменения

2022-02-14 22:48 UTC, JustShooter commented on src/main/java/linkedList/MyLinkedList.java
> +        for(int i = 0; i > index; i--)
Второй цикл убери.
Тело цикла всегда нужно окружать фигурными скобками:
for () {

}

2022-02-14 22:48 UTC, JustShooter commented on src/main/java/linkedList/MyLinkedList.java
> +        listFirst.next = listFirst.prev;
listFirst.next = listFirst.prev;
эта строчка не нужна.
return можно делать сразу
return listFirst.item;

2022-02-25 19:18 UTC, closed without merging

2022-02-25 19:19 UTC, iGeorgiy97 commented
Pull Request is closed